--------------------------------------------------------
--  DDL for Table CALIBER_TRAINER
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_TRAINER"
   (	"TRAINER_ID" NUMBER(10,0),
	"EMAIL" VARCHAR2(255 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"TIER" VARCHAR2(255 CHAR),
	"TITLE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_J0BB2CL63LSYCQ2N5AJ3LD22A
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."UK_J0BB2CL63LSYCQ2N5AJ3LD22A" ON "CALIBER"."CALIBER_TRAINER" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006875
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006875" ON "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TRAINER
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD CONSTRAINT "UK_J0BB2CL63LSYCQ2N5AJ3LD22A" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD PRIMARY KEY ("TRAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CALIBER_ADDRESS
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_ADDRESS"
   (    "ADDRESS_ID" NUMBER(10,0),
    "ADDRESS_STREET" VARCHAR2(255 CHAR),
    "ADDRESS_CITY" VARCHAR2(63 CHAR),
    "ADDRESS_STATE" VARCHAR2(2 CHAR),
    "ADDRESS_ZIPCODE" VARCHAR2(15 CHAR),
    "ADDRESS_COMPANY" VARCHAR2(255 CHAR),
    "ACTIVE" NUMBER(1,0) DEFAULT 1
   )SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CALIBER.CALIBER_ADDRESS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table CALIBER_ADDRESS
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_ADDRESS" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ADDRESS" ADD PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_BATCH
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_BATCH"
   (	"BATCH_ID" NUMBER(10,0),
	"BORDERLINE_GRADE_THRESHOLD" NUMBER(5,0),
	"END_DATE" DATE,
	"GOOD_GRADE_THRESHOLD" NUMBER(5,0),
	"LOCATION" VARCHAR2(255 CHAR),
	"SKILL_TYPE" VARCHAR2(255 CHAR),
	"START_DATE" DATE,
	"TRAINING_NAME" VARCHAR2(255 CHAR),
	"TRAINING_TYPE" VARCHAR2(255 CHAR),
	"NUMBER_OF_WEEKS" NUMBER(10,0),
	"CO_TRAINER_ID" NUMBER(10,0),
	"TRAINER_ID" NUMBER(10,0),
	"RESOURCE_ID" VARCHAR2(255 CHAR),
	"ADDRESS_ID" NUMBER(10,0),
	"GRADED_WEEKS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006856
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006856" ON "CALIBER"."CALIBER_BATCH" ("BATCH_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_BATCH
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("NUMBER_OF_WEEKS" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_BATCH
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_35QJTOMOM338V680F3XKO7PLH" FOREIGN KEY ("TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_4IDDE4FODT9VMU6CIXCQ4S2P1" FOREIGN KEY ("CO_TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_BATCH_ADDRESS" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "CALIBER"."CALIBER_ADDRESS" ("ADDRESS_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_CATEGORY
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_CATEGORY"
   (	"CATEGORY_ID" NUMBER(10,0),
	"SKILL_CATEGORY" VARCHAR2(255 CHAR),
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006858
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006858" ON "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_CATEGORY
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CALIBER_ASSESSMENT
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_ASSESSMENT"
   (	"ASSESSMENT_ID" NUMBER(19,0),
	"RAW_SCORE" NUMBER(10,0),
	"ASSESSMENT_TITLE" VARCHAR2(255 CHAR),
	"ASSESSMENT_TYPE" VARCHAR2(255 CHAR),
	"WEEK_NUMBER" NUMBER(5,0),
	"BATCH_ID" NUMBER(10,0),
	"ASSESSMENT_CATEGORY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006848
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006848" ON "CALIBER"."CALIBER_ASSESSMENT" ("ASSESSMENT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_ASSESSMENT
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("RAW_SCORE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD PRIMARY KEY ("ASSESSMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("WEEK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_ASSESSMENT
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD CONSTRAINT "FK_3NBC8UK6IAM68O6DK4XVMRWL2" FOREIGN KEY ("ASSESSMENT_CATEGORY")
	  REFERENCES "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD CONSTRAINT "FK_83R77WO51CP74YVUFSLYP3E1M" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_TRAINEE
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_TRAINEE"
   (	"TRAINEE_ID" NUMBER(10,0),
	"TRAINEE_EMAIL" VARCHAR2(255 CHAR),
	"TRAINEE_NAME" VARCHAR2(255 CHAR),
	"TRAINING_STATUS" VARCHAR2(255 CHAR),
	"BATCH_ID" NUMBER(10,0),
	"PHONE_NUMBER" VARCHAR2(255 CHAR),
	"PROFILE_URL" VARCHAR2(255 CHAR),
	"SKYPE_ID" VARCHAR2(255 CHAR),
	"RESOURCE_ID" VARCHAR2(255 CHAR),
    "FLAG_NOTES" VARCHAR2 (400 CHAR),
    "FLAG_STATUS" VARCHAR2(255 CHAR) DEFAULT 'NONE'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index SYS_C006870
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006870" ON "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TRAINEE
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD PRIMARY KEY ("TRAINEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_TRAINEE
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD CONSTRAINT "FK_I6XQ8I1717FWXU7UQBXHMGOWC" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
/

--------------------------------------------------------
--  DDL for Table CALIBER_GRADE
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_GRADE"
   (	"GRADE_ID" NUMBER(19,0),
	"DATE_RECEIVED" TIMESTAMP (6),
	"SCORE" FLOAT(126),
	"ASSESSMENT_ID" NUMBER(19,0),
	"TRAINEE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006864
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006864" ON "CALIBER"."CALIBER_GRADE" ("GRADE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_GRADE
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD PRIMARY KEY ("GRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("DATE_RECEIVED" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("GRADE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_GRADE
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD CONSTRAINT "FK_7GF9T26KCY85A3XMQLA8TF4R1" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD CONSTRAINT "FK_JCQEJLMKF8JA574MPH22YL483" FOREIGN KEY ("ASSESSMENT_ID")
	  REFERENCES "CALIBER"."CALIBER_ASSESSMENT" ("ASSESSMENT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_NOTE
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_NOTE"
   (	"NOTE_ID" NUMBER(10,0),
	"NOTE_CONTENT" VARCHAR2(4000 CHAR),
	"MAX_VISIBILITY" NUMBER(10,0),
	"IS_QC_FEEDBACK" NUMBER(1,0),
	"QC_STATUS" VARCHAR2(255 CHAR),
	"NOTE_TYPE" VARCHAR2(255 CHAR),
	"WEEK_NUMBER" NUMBER(5,0),
	"BATCH_ID" NUMBER(10,0),
	"TRAINEE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006867
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C006867" ON "CALIBER"."CALIBER_NOTE" ("NOTE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_NOTE
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD PRIMARY KEY ("NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_NOTE" MODIFY ("IS_QC_FEEDBACK" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_NOTE" MODIFY ("NOTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_NOTE
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD CONSTRAINT "FK_I8GMTI8EP44N7VE6KB1JK5CR3" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD CONSTRAINT "FK_QU8BU6BS63XBDT5OUTD7VD4DJ" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_PANEL
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_PANEL" 
   (	"PANEL_ID" NUMBER(10,0), 
	"ASSOCIATE_INTRO" VARCHAR2(1000 CHAR), 
	"COMMUNICATION_SKILLS" VARCHAR2(1000 CHAR), 
	"DURATION" VARCHAR2(255 CHAR), 
	"INTERVIEW_FORMAT" VARCHAR2(255 CHAR), 
	"INTERNET_CONNECTIVITY" VARCHAR2(255 CHAR), 
	"INTERVIEW_DATE" TIMESTAMP (6), 
	"OVERALL_FEEDBACK" VARCHAR2(1000 CHAR), 
	"PANEL_ROUND" NUMBER(10,0), 
	"PROJECT_ONE_DESCRIPTION" VARCHAR2(1000 CHAR), 
	"PROJECT_THREE_DESCRIPTION" VARCHAR2(1000 CHAR), 
	"PROJECT_TWO_DESCRIPTION" VARCHAR2(1000 CHAR), 
	"RECORDING_CONSENT" VARCHAR2(20 CHAR), 
	"RECORDING_LINK" VARCHAR2(255 CHAR), 
	"PANEL_STATUS" VARCHAR2(20 CHAR), 
	"PANELIST_ID" NUMBER(10,0), 
	"TRAINEE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011400
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C0011400" ON "CALIBER"."CALIBER_PANEL" ("PANEL_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_PANEL
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_PANEL" ADD PRIMARY KEY ("PANEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_PANEL" ADD CHECK (PANEL_ROUND>=1) ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_PANEL" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL" MODIFY ("PANELIST_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL" MODIFY ("PANEL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL" MODIFY ("PANEL_ROUND" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL" MODIFY ("INTERVIEW_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL" MODIFY ("PANEL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_PANEL
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_PANEL" ADD CONSTRAINT "FK_JFR6OCW09DW69AAIGW4U7QRP5" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_PANEL" ADD CONSTRAINT "FK_QBCLCSTJGHPAYHWIAGX8HVX4V" FOREIGN KEY ("PANELIST_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_PANEL_FEEDBACK
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK"
   (	"PANEL_FEEDBACK_ID" NUMBER(19,0),
	"PANELIST_COMMENTS" VARCHAR2(1000 CHAR),
	"PANEL_RESULT" VARCHAR2(20 CHAR),
	"PANEL_STATUS" VARCHAR2(20 CHAR),
	"PANEL_ID" NUMBER(10,0),
	"CATEGORY_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011407
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C0011407" ON "CALIBER"."CALIBER_PANEL_FEEDBACK" ("PANEL_FEEDBACK_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_PANEL_FEEDBACK
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" ADD PRIMARY KEY ("PANEL_FEEDBACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" MODIFY ("PANEL_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" MODIFY ("PANEL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" MODIFY ("PANEL_RESULT" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" MODIFY ("PANELIST_COMMENTS" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" MODIFY ("PANEL_FEEDBACK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_PANEL_FEEDBACK
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" ADD CONSTRAINT "FK_DUQ9ETOU1QMJBNMD0D43NX0TC" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_PANEL_FEEDBACK" ADD CONSTRAINT "FK_GQXJIXAFOY11XR6L8BMPSTV0D" FOREIGN KEY ("PANEL_ID")
	  REFERENCES "CALIBER"."CALIBER_PANEL" ("PANEL_ID") ENABLE;
--------------------------------------------------------
--  DDL for Sequence TRAINER_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."TRAINER_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  ALTER TABLE CALIBER_TRAINEE
--------------------------------------------------------
ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD RECRUITER_NAME VARCHAR2(255 CHAR) NULL;
ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD COLLEGE VARCHAR2(255 CHAR) NULL;
ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD DEGREE VARCHAR2(255 CHAR) NULL;
ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD MAJOR VARCHAR2(255 CHAR) NULL;
ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD TECH_SCREENER_NAME VARCHAR2(255 CHAR) NULL;
ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD REVPRO_PROJECT_COMPLETION NUMBER(10) NULL;


-- NEW TABLES AND COLUMNS FOR TRAIN THE TRAINER CHECKLIST
--------------------------------------------------------
--  DDL for Table CALIBER_TASK
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_TASK"
   (	"TASK_ID" NUMBER(10,0),
	"IS_ACTIVE" NUMBER(1,0),
	"TASK_DESCRIPTION" VARCHAR2(255 CHAR),
	"TASK_PRIORITY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011695
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C0011695" ON "CALIBER"."CALIBER_TASK" ("TASK_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TASK
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_TASK" ADD PRIMARY KEY ("TASK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TASK" MODIFY ("TASK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CALIBER_TASK_COMPLETION
--------------------------------------------------------
  CREATE TABLE "CALIBER"."CALIBER_TASK_COMPLETION"
   (	"TASK_COMPLETION_ID" NUMBER(10,0),
	"COMPLETION_DATE" DATE,
	"CHECKED_BY" NUMBER(10,0),
	"TASK_ID" NUMBER(10,0) NOT NULL,
	"TRAINER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011700
--------------------------------------------------------
  CREATE UNIQUE INDEX "CALIBER"."SYS_C0011700" ON "CALIBER"."CALIBER_TASK_COMPLETION" ("TASK_COMPLETION_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TASK_COMPLETION
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" ADD PRIMARY KEY ("TASK_COMPLETION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" MODIFY ("CHECKED_BY" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" MODIFY ("COMPLETION_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" MODIFY ("TASK_COMPLETION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_TASK_COMPLETION
--------------------------------------------------------
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" ADD CONSTRAINT "FK_3FBXNU2RHAHET3WHDCLOX75DL" FOREIGN KEY ("TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" ADD CONSTRAINT "FK_N0TMAP4M8FTAFKP3FUKXXL6T3" FOREIGN KEY ("CHECKED_BY")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TASK_COMPLETION" ADD CONSTRAINT "FK_QQRRVSYR2UDC3M2T5NJI03TQH" FOREIGN KEY ("TASK_ID")
	  REFERENCES "CALIBER"."CALIBER_TASK" ("TASK_ID") ENABLE;
-------------TRAINER-------------
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'patrick.walsh@revature.com', 'Patrick Walsh', 'Lead Trainer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'pjw6193@hotmail.com', 'Dan Pickles', 'Lead Trainer', 'ROLE_VP');
-------------TRAINER END-------------
COMMIT;
--------------------------------------------------------
--  DDL for Sequence ASSESSMENT_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."ASSESSMENT_ID_SEQUENCE"  MINVALUE 3080 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3080 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BATCH_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."BATCH_ID_SEQUENCE"  MINVALUE 2210 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2210 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."CATEGORY_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GRADE_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."GRADE_ID_SEQUENCE"  MINVALUE 3000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTE_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."NOTE_ID_SEQUENCE"  MINVALUE 6500 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6500 CACHE 20 NOORDER  NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence TRAINEE_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."TRAINEE_ID_SEQUENCE"  MINVALUE 5600 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5600 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADDRESS_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."ADDRESS_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PANEL_FEEDBACK_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."PANEL_FEEDBACK_ID_SEQUENCE"  MINVALUE 141 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PANEL_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."PANEL_ID_SEQUENCE"  MINVALUE 71 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 71 CACHE 20 NOORDER  NOCYCLE ;
   --------------------------------------------------------
--  DDL for Sequence TASK_COMPLETION_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."TASK_COMPLETION_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TASK_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "CALIBER"."TASK_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
