--------------------------------------------------------
--  DDL for Table CALIBER_TIER
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_TIER" 
   (	"TIER_ID" NUMBER(5,0), 
	"RANKING" NUMBER(5,0), 
	"TIER" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010440
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010440" ON "CALIBER"."CALIBER_TIER" ("TIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TIER
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TIER" ADD PRIMARY KEY ("TIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TIER" MODIFY ("TIER" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TIER" MODIFY ("RANKING" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TIER" MODIFY ("TIER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CALIBER_TRAINER
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_TRAINER" 
   (	"TRAINER_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"SF_ACCOUNT" VARCHAR2(255 CHAR), 
	"SF_AUTHENTICATION_TOKEN" VARCHAR2(255 CHAR), 
	"SF_REFRESH_TOKEN" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(255 CHAR), 
	"TIER" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010452
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010452" ON "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_J0BB2CL63LSYCQ2N5AJ3LD22A
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."UK_J0BB2CL63LSYCQ2N5AJ3LD22A" ON "CALIBER"."CALIBER_TRAINER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TRAINER
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD CONSTRAINT "UK_J0BB2CL63LSYCQ2N5AJ3LD22A" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD PRIMARY KEY ("TRAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TIER" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("SF_REFRESH_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("SF_AUTHENTICATION_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("SF_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_TRAINER
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD CONSTRAINT "FK_9WQCIP8LW28SG5QVBN1R05NVV" FOREIGN KEY ("TIER")
	  REFERENCES "CALIBER"."CALIBER_TIER" ("TIER_ID") ENABLE;


  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD CONSTRAINT "FK_I6XQ8I1717FWXU7UQBXHMGOWC" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_BATCH
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_BATCH" 
   (	"BATCH_ID" NUMBER(10,0), 
	"BORDERLINE_GRADE_THRESHOLD" NUMBER(5,0), 
	"END_DATE" TIMESTAMP (6), 
	"GOOD_GRADE_THRESHOLD" NUMBER(5,0), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"SKILL_TYPE" VARCHAR2(255 CHAR), 
	"START_DATE" TIMESTAMP (6), 
	"TRAINING_NAME" VARCHAR2(255 CHAR), 
	"TRAINING_TYPE" VARCHAR2(255 CHAR), 
	"NUMBER_OF_WEEKS" NUMBER(5,0), 
	"CO_TRAINER_ID" NUMBER(10,0), 
	"TRAINER_ID" NUMBER(10,0), 
	"BENCHMARK_END_DATE" TIMESTAMP (6), 
	"BENCHMARK_START_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010427
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010427" ON "CALIBER"."CALIBER_BATCH" ("BATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_BATCH
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("BATCH_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_BATCH
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_35QJTOMOM338V680F3XKO7PLH" FOREIGN KEY ("TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_4IDDE4FODT9VMU6CIXCQ4S2P1" FOREIGN KEY ("CO_TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_TRAINEE
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_TRAINEE" 
   (	"TRAINEE_ID" NUMBER(10,0), 
	"TRAINEE_EMAIL" VARCHAR2(255 CHAR), 
	"TRAINEE_NAME" VARCHAR2(255 CHAR), 
	"TRAINING_STATUS" VARCHAR2(255 CHAR), 
	"BATCH_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010443
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010443" ON "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TRAINEE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD PRIMARY KEY ("TRAINEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_TRAINEE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD CONSTRAINT "FK_I6XQ8I1717FWXU7UQBXHMGOWC" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_CATEGORY
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_CATEGORY" 
   (	"CATEGORY_ID" NUMBER(10,0), 
	"SKILL_CATEGORY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010429
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010429" ON "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_CATEGORY
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CALIBER_ASSESSMENT
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_ASSESSMENT" 
   (	"ASSESSMENT_ID" NUMBER(19,0), 
	"RAW_SCORE" NUMBER(10,0), 
	"ASSESSMENT_TITLE" VARCHAR2(255 CHAR), 
	"ASSESSMENT_TYPE" VARCHAR2(255 CHAR), 
	"WEEK_NUMBER" NUMBER(5,0), 
	"BATCH_ID" NUMBER(10,0), 
	"ASSESSMENT_CATEGORY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010421
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010421" ON "CALIBER"."CALIBER_ASSESSMENT" ("ASSESSMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_ASSESSMENT
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD PRIMARY KEY ("ASSESSMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_TITLE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_ASSESSMENT
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD CONSTRAINT "FK_3NBC8UK6IAM68O6DK4XVMRWL2" FOREIGN KEY ("ASSESSMENT_CATEGORY")
	  REFERENCES "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD CONSTRAINT "FK_83R77WO51CP74YVUFSLYP3E1M" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_NOTE
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_NOTE" 
   (	"NOTE_ID" NUMBER(10,0), 
	"NOTE_CONTENT" VARCHAR2(255 CHAR), 
	"WEEK_NUMBER" NUMBER(5,0), 
	"BATCH_ID" NUMBER(10,0), 
	"TRAINEE_ID" NUMBER(10,0), 
	"MAX_VISIBILITY" NUMBER(10,0), 
	"NOTE_TYPE" NUMBER(10,0), 
	"IS_QC_FEEDBACK" NUMBER(1,0), 
	"QC_STATUS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010436
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010436" ON "CALIBER"."CALIBER_NOTE" ("NOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_NOTE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD PRIMARY KEY ("NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_NOTE" MODIFY ("WEEK_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_NOTE" MODIFY ("NOTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_NOTE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD CONSTRAINT "FK_I8GMTI8EP44N7VE6KB1JK5CR3" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD CONSTRAINT "FK_QU8BU6BS63XBDT5OUTD7VD4DJ" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_GRADE
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_GRADE" 
   (	"GRADE_ID" NUMBER(19,0), 
	"DATE_RECEIVED" TIMESTAMP (6), 
	"SCORE" NUMBER(10,0), 
	"ASSESSMENT_ID" NUMBER(19,0), 
	"TRAINEE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010433
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010433" ON "CALIBER"."CALIBER_GRADE" ("GRADE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_GRADE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD PRIMARY KEY ("GRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("GRADE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_GRADE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD CONSTRAINT "FK_7GF9T26KCY85A3XMQLA8TF4R1" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD CONSTRAINT "FK_JCQEJLMKF8JA574MPH22YL483" FOREIGN KEY ("ASSESSMENT_ID")
	  REFERENCES "CALIBER"."CALIBER_ASSESSMENT" ("ASSESSMENT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Sequence ASSESSMENT_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."ASSESSMENT_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BATCH_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."BATCH_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE; 
   --------------------------------------------------------
--  DDL for Sequence CATEGORY_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."CATEGORY_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GRADE_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."GRADE_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTE_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."NOTE_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QC_STATUS_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."QC_STATUS_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIER_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."TIER_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAINEE_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."TRAINEE_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE; 
   --------------------------------------------------------
--  DDL for Sequence TRAINER_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."TRAINER_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE; 
   --------------------------------------------------------
--  DDL for Sequence WEEK_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CALIBER"."WEEK_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   -------------TIER----------------
INSERT INTO CALIBER_TIER(TIER_ID, RANKING, TIER) VALUES (CALIBER.TIER_ID_SEQUENCE.NEXTVAL, 1, 'ROLE_VP');
INSERT INTO CALIBER_TIER(TIER_ID, RANKING, TIER) VALUES (CALIBER.TIER_ID_SEQUENCE.NEXTVAL, 2, 'ROLE_QC');
INSERT INTO CALIBER_TIER(TIER_ID, RANKING, TIER) VALUES (CALIBER.TIER_ID_SEQUENCE.NEXTVAL, 3, 'ROLE_TRAINER');
-------------TIER END-------------


-------------TRAINER-------------
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, SF_ACCOUNT, SF_AUTHENTICATION_TOKEN, SF_REFRESH_TOKEN, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'eliobr@gmail.com', 'Elijah	Obrien', 'account', 'token', 'refresh_token', 'Vice President of the Training Department', 1);
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, SF_ACCOUNT, SF_AUTHENTICATION_TOKEN, SF_REFRESH_TOKEN, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'agha@gmail.com', 'Agnes	Hardy', 'account', 'token', 'refresh_token', 'Head of the Quality Department', 2);
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, SF_ACCOUNT, SF_AUTHENTICATION_TOKEN, SF_REFRESH_TOKEN, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'pjw6193@hotmail.com', 'Patrick Walsh', 'account', 'token', 'refresh_token', 'Senior Trainer', 3);
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, SF_ACCOUNT, SF_AUTHENTICATION_TOKEN, SF_REFRESH_TOKEN, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'knorton@gmail.com', 'Katie	Norton', 'account', 'token', 'refresh_token', 'Senior Trainer', 3);
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, SF_ACCOUNT, SF_AUTHENTICATION_TOKEN, SF_REFRESH_TOKEN, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'dwebb@gmail.com', 'Diana Webb', 'account', 'token', 'refresh_token', 'Senior Trainer', 3);
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, SF_ACCOUNT, SF_AUTHENTICATION_TOKEN, SF_REFRESH_TOKEN, TITLE, TIER)
  VALUES(CALIBER.TRAINER_ID_SEQUENCE.NEXTVAL, 'leelane@gmail.com', 'Lee Lane', 'account', 'token', 'refresh_token', 'Junior Trainer', 3);
-------------TRAINER END-------------
-------------CATEGORY (TRAINING MODULE)----------------
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Java');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'SQL');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Servlet');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'JSP');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'XML');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Git');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'JUnit');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Maven');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'JDBC');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'HTML');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'CSS');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'JavaScript');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'jQuery');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'AJAX');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'UNIX');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'AWS');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Jenkins');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Hibernate');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL,'Spring');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'SOAP');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'REST');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'AngularJS');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Selenium');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Cucumber');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'UFT');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Python');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Robot Framework');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'ALM');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'SDLC');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Agile');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Testing');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'VBScript');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'SOAP UI');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'TestNG');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Chef');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Docker');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Kafka');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Microservices');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'NoSQL');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'C#');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'ASP.NET');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'ADO.NET');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'Entity Framework');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'MSBuild');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'WPF');
INSERT INTO CALIBER_CATEGORY VALUES (CATEGORY_ID_SEQUENCE.NEXTVAL, 'WCF');
-------------CATEGORY (TRAINING MODULE) END----------------
