package com.revature.caliber.assessments.service.implementations;

import com.revature.caliber.assessments.beans.Assessment;
import com.revature.caliber.assessments.service.AssessmentService;
import org.apache.log4j.Logger;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.FileSystemXmlApplicationContext;
import org.springframework.transaction.annotation.Transactional;

import java.util.Set;

import static junit.framework.TestCase.assertNotNull;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;

public class AssessmentServiceTest {


    private static AbstractApplicationContext context;
    private static Logger log;
    private static AssessmentService assessmentService;
    //ID of test Assessment
    private static long assessmentId;

    @BeforeClass
    public static void setUp() {

        context = new FileSystemXmlApplicationContext("src/main/webapp/WEB-INF/beans.xml");
        // rootLogger is for debugging purposes
        log = Logger.getRootLogger();

        log.debug("Starting AssessmentServiceTest");

        assessmentService = (AssessmentService) context.getBean("assessmentService");

        populateTable();
    }

    /**
     * Populates table with Assessment used for testing
     */
    @Transactional
    private static void populateTable() {
        //Adding required data
        Assessment assessment = new Assessment();
        //id is auto generated by hibernate
        assessment.setAssessmentId(1);
        assessment.setTitle("Week 1 Test");
        assessment.setBatch(1);
        assessment.setRawScore(100);
        assessment.setType("LMS");
        assessment.setWeek(1);

        assessmentId = assessmentService.insert(assessment);
    }

    @AfterClass
    public static void cleanUp() {

        Assessment assessment = assessmentService.getById(assessmentId);

        if (assessment != null) {
            assessmentService.delete(assessment);
            assessment = assessmentService.getById(assessmentId);
            assertNull(assessment);
        }

        log.debug("Ending AssessmentServiceTest");
    }

    @Test
    public void getAll() {
        log.debug("Starting getAllAssessmentsTest");

        Set<Assessment> assessments = assessmentService.getAll();
        assertFalse(assessments.isEmpty());

        log.debug("Ending getAllAssessmentsTest");
    }

    @Test
    public void getById() {
        long id = assessmentId;
        log.debug("Starting getAssessmentById = " + id);

        Assessment assessment = assessmentService.getById(id);
        assertNotNull(assessment);

        log.debug("Ending getAssessmentById");
    }

    @Test
    public void getByWeekId() {
        long weekId = 1;
        log.debug("Starting getAssessmentsByWeekId with id = " + weekId);

        Set<Assessment> assessments = assessmentService.getByWeekId(weekId);
        assertFalse(assessments.isEmpty());

        log.debug("Ending getByWeekId");
    }

    @Test
    public void insert() {
        log.debug("Starting insertAssessment");

        //create new Assessment to insert
        Assessment assessment = new Assessment();
        assessment.setAssessmentId(1);
        assessment.setTitle("Week 1 Test");
        assessment.setBatch(1);
        assessment.setRawScore(100);
        assessment.setType("LMS");
        assessment.setWeek(1);

        long createdAssessmentId = assessmentService.insert(assessment);

        //check to see if Assessment was created
        Assessment fetchedAssessment = assessmentService.getById(createdAssessmentId);
        assertNotNull(fetchedAssessment);

        //delete the created Assessment
        assessmentService.delete(fetchedAssessment);
        fetchedAssessment = null; //set to null to reuse in next line
        fetchedAssessment = assessmentService.getById(createdAssessmentId);
        assertNull(fetchedAssessment);

        log.debug("Ending insertAssessment");
    }

    @Test
    public void delete() {
        long id = assessmentId;
        log.debug("Starting test to fetch, delete, then fetch Assessment with id = " + id
                + "to make sure delete is functional");

        Assessment assessment = assessmentService.getById(id);

        if (assessment != null) {
            assessmentService.delete(assessment);
            assessment = assessmentService.getById(id);
            assertNull(assessment);
        }

        //populating table again for other tests
        populateTable();
    }
}
