-------------ADDRESS DATA----------------
Insert into CALIBER_ADDRESS (ADDRESS_ID,ADDRESS_STREET,ADDRESS_CITY,ADDRESS_STATE,ADDRESS_ZIPCODE,ADDRESS_COMPANY,ACTIVE) values (ADDRESS_ID_SEQUENCE.NEXTVAL,'65-30 Kissena Blvd, CEP Hall 2','Queens','NY','11367','Tech Incubator at Queens College',1);
Insert into CALIBER_ADDRESS (ADDRESS_ID,ADDRESS_STREET,ADDRESS_CITY,ADDRESS_STATE,ADDRESS_ZIPCODE,ADDRESS_COMPANY,ACTIVE) values (ADDRESS_ID_SEQUENCE.NEXTVAL,'11730 Plaza America Drive, 2nd Floor','Reston','VA','20190','Revature LLC',1);
COMMIT;