--------------------------------------------------------
-- Configures the Caliber schema
-- Author: Patrick Walsh
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table CALIBER_TRAINER
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_TRAINER" 
   (	"TRAINER_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"TIER" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010597
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010597" ON "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_J0BB2CL63LSYCQ2N5AJ3LD22A
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."UK_J0BB2CL63LSYCQ2N5AJ3LD22A" ON "CALIBER"."CALIBER_TRAINER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TRAINER
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD CONSTRAINT "UK_J0BB2CL63LSYCQ2N5AJ3LD22A" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" ADD PRIMARY KEY ("TRAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINER" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CALIBER_BATCH
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_BATCH" 
   (	"BATCH_ID" NUMBER(10,0), 
   "RESOURCE_ID" VARCHAR2(63) unique,
	"BORDERLINE_GRADE_THRESHOLD" NUMBER(5,0), 
	"END_DATE" DATE, 
	"GOOD_GRADE_THRESHOLD" NUMBER(5,0), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"SKILL_TYPE" VARCHAR2(255 CHAR), 
	"START_DATE" DATE, 
	"TRAINING_NAME" VARCHAR2(255 CHAR), 
	"TRAINING_TYPE" VARCHAR2(255 CHAR), 
	"NUMBER_OF_WEEKS" NUMBER(10,0), 
	"CO_TRAINER_ID" NUMBER(10,0), 
	"TRAINER_ID" NUMBER(10,0),
  
  CONSTRAINT CALIBER_BATCH UNIQUE ()
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010578
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010578" ON "CALIBER"."CALIBER_BATCH" ("BATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_BATCH
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD PRIMARY KEY ("BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("NUMBER_OF_WEEKS" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_BATCH" MODIFY ("BATCH_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_BATCH
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_35QJTOMOM338V680F3XKO7PLH" FOREIGN KEY ("TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_BATCH" ADD CONSTRAINT "FK_4IDDE4FODT9VMU6CIXCQ4S2P1" FOREIGN KEY ("CO_TRAINER_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINER" ("TRAINER_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_CATEGORY
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_CATEGORY" 
   (	"CATEGORY_ID" NUMBER(10,0), 
	"SKILL_CATEGORY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010580
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010580" ON "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_CATEGORY
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CALIBER_ASSESSMENT
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_ASSESSMENT" 
   (	"ASSESSMENT_ID" NUMBER(19,0), 
	"RAW_SCORE" NUMBER(10,0), 
	"ASSESSMENT_TITLE" VARCHAR2(255 CHAR), 
	"ASSESSMENT_TYPE" VARCHAR2(255 CHAR) NOT NULL, 
	"WEEK_NUMBER" NUMBER(5,0) NOT NULL, 
	"BATCH_ID" NUMBER(10,0) NOT NULL, 
	"ASSESSMENT_CATEGORY" NUMBER(10,0) NOT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010570
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010570" ON "CALIBER"."CALIBER_ASSESSMENT" ("ASSESSMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_ASSESSMENT
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD PRIMARY KEY ("ASSESSMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_ASSESSMENT
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD CONSTRAINT "FK_3NBC8UK6IAM68O6DK4XVMRWL2" FOREIGN KEY ("ASSESSMENT_CATEGORY")
	  REFERENCES "CALIBER"."CALIBER_CATEGORY" ("CATEGORY_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_ASSESSMENT" ADD CONSTRAINT "FK_83R77WO51CP74YVUFSLYP3E1M" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_TRAINEE
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_TRAINEE" 
   (	"TRAINEE_ID" NUMBER(10,0), 
   "RESOURCE_ID" VARCHAR2(63) unique,
	"TRAINEE_EMAIL" VARCHAR2(255 CHAR) NOT NULL, 
	"TRAINEE_NAME" VARCHAR2(255 CHAR) NOT NULL, 
	"TRAINING_STATUS" VARCHAR2(255 CHAR) NOT NULL, 
	"BATCH_ID" NUMBER(10,0), 
	"PHONE_NUMBER" VARCHAR2(255 CHAR), 
	"PROFILE_URL" VARCHAR2(255 CHAR), 
	"SKYPE_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010592
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010592" ON "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_TRAINEE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD PRIMARY KEY ("TRAINEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" MODIFY ("TRAINEE_EMAIL" NOT NULL ENABLE);
  alter table "CALIBER"."CALIBER_TRAINEE" add constraint TRAINEE_UNIQUE_EMAIL unique("TRAINEE_EMAIL") ;
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_TRAINEE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_TRAINEE" ADD CONSTRAINT "FK_I6XQ8I1717FWXU7UQBXHMGOWC" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_GRADE
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_GRADE" 
   (	"GRADE_ID" NUMBER(19,0), 
	"DATE_RECEIVED" TIMESTAMP (6), 
	"SCORE" FLOAT(126), 
	"ASSESSMENT_ID" NUMBER(19,0), 
	"TRAINEE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010586
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010586" ON "CALIBER"."CALIBER_GRADE" ("GRADE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_GRADE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD PRIMARY KEY ("GRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("TRAINEE_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("ASSESSMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("DATE_RECEIVED" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_GRADE" MODIFY ("GRADE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_GRADE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD CONSTRAINT "FK_7GF9T26KCY85A3XMQLA8TF4R1" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_GRADE" ADD CONSTRAINT "FK_JCQEJLMKF8JA574MPH22YL483" FOREIGN KEY ("ASSESSMENT_ID")
	  REFERENCES "CALIBER"."CALIBER_ASSESSMENT" ("ASSESSMENT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Table CALIBER_NOTE
--------------------------------------------------------

  CREATE TABLE "CALIBER"."CALIBER_NOTE" 
   (	"NOTE_ID" NUMBER(10,0), 
	"NOTE_CONTENT" VARCHAR2(4000 CHAR), 
	"MAX_VISIBILITY" NUMBER(10,0), 
	"IS_QC_FEEDBACK" NUMBER(1,0), 
	"QC_STATUS" VARCHAR2(255 CHAR), 
	"NOTE_TYPE" VARCHAR2(255 CHAR), 
	"WEEK_NUMBER" NUMBER(5,0), 
	"BATCH_ID" NUMBER(10,0), 
	"TRAINEE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010589
--------------------------------------------------------

  CREATE UNIQUE INDEX "CALIBER"."SYS_C0010589" ON "CALIBER"."CALIBER_NOTE" ("NOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIBER_NOTE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD PRIMARY KEY ("NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_NOTE" MODIFY ("IS_QC_FEEDBACK" NOT NULL ENABLE);
  ALTER TABLE "CALIBER"."CALIBER_NOTE" MODIFY ("NOTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CALIBER_NOTE
--------------------------------------------------------

  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD CONSTRAINT "FK_I8GMTI8EP44N7VE6KB1JK5CR3" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "CALIBER"."CALIBER_BATCH" ("BATCH_ID") ENABLE;
  ALTER TABLE "CALIBER"."CALIBER_NOTE" ADD CONSTRAINT "FK_QU8BU6BS63XBDT5OUTD7VD4DJ" FOREIGN KEY ("TRAINEE_ID")
	  REFERENCES "CALIBER"."CALIBER_TRAINEE" ("TRAINEE_ID") ENABLE;
