--------------------------------------------------------
-- Guts out all of the test data to prepare for next test
-- Author: Patrick Walsh
--------------------------------------------------------

DROP SEQUENCE CALIBER.ASSESSMENT_ID_SEQUENCE;
DROP SEQUENCE CALIBER.BATCH_ID_SEQUENCE;
DROP SEQUENCE CALIBER.CATEGORY_ID_SEQUENCE;
DROP SEQUENCE CALIBER.GRADE_ID_SEQUENCE;
DROP SEQUENCE CALIBER.NOTE_ID_SEQUENCE;
DROP SEQUENCE CALIBER.TRAINEE_ID_SEQUENCE;
DROP SEQUENCE CALIBER.TRAINER_ID_SEQUENCE;

DELETE FROM CALIBER.CALIBER_GRADE;
DELETE FROM CALIBER.CALIBER_NOTE;
DELETE FROM CALIBER.CALIBER_ASSESSMENT;
DELETE FROM CALIBER.CALIBER_CATEGORY;
DELETE FROM CALIBER.CALIBER_TRAINEE;
DELETE FROM CALIBER.CALIBER_BATCH;
DELETE FROM CALIBER_TRAINER;
COMMIT;