pipeline {
  agent any

  stages {
     
     stage ("mvnw"){
     	   steps {
	   	 sh "./mvnw clean install -Dmaven.test.skip=true"
		 }
     }
/*    stage ("Stopping"){
    	steps {
	  sh "docker-compose stop"
	}
  } 
   stage ("Clean") {
    	steps {
	  sh "mvn clean"
	}
   }
   stage ("Install") {
        steps {
	    sh "mvn install"
	  }
    }
    stage ("Package"){
        steps {
	   sh "mvn package"
  	}
    }
    stage ("Deploy Containers") {
    	steps {
	   sh "docker-compose up -d"
 	}
    }
*/
  }
}